# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            # Checkout
            -   uses: actions/checkout@v2
            # Cache
            -   uses: actions/cache@v2
                with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
                    restore-keys: |
                        ${{ runner.os }}-pip-
            # Setup python
            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            # Setup dependencies
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install flake8 black mypy pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            # Format
            -   name: Check format
                run: black --check aioportforward.py
            # Types
            -   name: Check types
                run: mypy aioportforward.py
            # Linting
            -   name: Lint with flake8
                run: |
                    # stop the build if there are Python syntax errors or undefined names
                    flake8 aioportforward.py --count --select=E9,F63,F7,F82 --show-source --statistics
                    # exit-zero treats all errors as warnings. Blacks default line length is 88 chars wide
                    flake8 aioportforward.py --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
            # Tests
            -   name: Test with pytest
                run: |
                    python -m pytest
